// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userinfo.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//通证类型
type TokenType int32

const (
	//默认参数（无效），0值尽量不要有任何意义，接收到0值做错误处理
	TokenType_Default TokenType = 0
	TokenType_BTC     TokenType = 1
	TokenType_EHT     TokenType = 2
)

var TokenType_name = map[int32]string{
	0: "Default",
	1: "BTC",
	2: "EHT",
}

var TokenType_value = map[string]int32{
	"Default": 0,
	"BTC":     1,
	"EHT":     2,
}

func (x TokenType) String() string {
	return proto.EnumName(TokenType_name, int32(x))
}

func (TokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{0}
}

//用户关系
type UserRelation struct {
	//发起者用户id
	FromUserId string `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	//目标用户Id
	ToUserId             string   `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRelation) Reset()         { *m = UserRelation{} }
func (m *UserRelation) String() string { return proto.CompactTextString(m) }
func (*UserRelation) ProtoMessage()    {}
func (*UserRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{0}
}

func (m *UserRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRelation.Unmarshal(m, b)
}
func (m *UserRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRelation.Marshal(b, m, deterministic)
}
func (m *UserRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRelation.Merge(m, src)
}
func (m *UserRelation) XXX_Size() int {
	return xxx_messageInfo_UserRelation.Size(m)
}
func (m *UserRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRelation.DiscardUnknown(m)
}

var xxx_messageInfo_UserRelation proto.InternalMessageInfo

func (m *UserRelation) GetFromUserId() string {
	if m != nil {
		return m.FromUserId
	}
	return ""
}

func (m *UserRelation) GetToUserId() string {
	if m != nil {
		return m.ToUserId
	}
	return ""
}

//用户通证资产
type TokenBalance struct {
	//用户id
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//通证类型
	TokenType TokenType `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=user.TokenType" json:"token_type,omitempty"`
	//积分数量
	Balance              float64  `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBalance) Reset()         { *m = TokenBalance{} }
func (m *TokenBalance) String() string { return proto.CompactTextString(m) }
func (*TokenBalance) ProtoMessage()    {}
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{1}
}

func (m *TokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBalance.Unmarshal(m, b)
}
func (m *TokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBalance.Marshal(b, m, deterministic)
}
func (m *TokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBalance.Merge(m, src)
}
func (m *TokenBalance) XXX_Size() int {
	return xxx_messageInfo_TokenBalance.Size(m)
}
func (m *TokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBalance proto.InternalMessageInfo

func (m *TokenBalance) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenBalance) GetTokenType() TokenType {
	if m != nil {
		return m.TokenType
	}
	return TokenType_Default
}

func (m *TokenBalance) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterEnum("user.TokenType", TokenType_name, TokenType_value)
	proto.RegisterType((*UserRelation)(nil), "user.UserRelation")
	proto.RegisterType((*TokenBalance)(nil), "user.TokenBalance")
}

func init() { proto.RegisterFile("userinfo.proto", fileDescriptor_785a78c34699a93d) }

var fileDescriptor_785a78c34699a93d = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x8b, 0x6a, 0x72, 0x44, 0x25, 0xf2, 0x42, 0x06, 0x86, 0xa8, 0x53, 0xd5, 0xc1,
	0x03, 0xbc, 0x41, 0x01, 0x09, 0x16, 0x06, 0xcb, 0xcc, 0x91, 0x4b, 0x2e, 0x52, 0x94, 0xe0, 0x0b,
	0x8e, 0x33, 0xe4, 0xed, 0x91, 0x1d, 0x25, 0x52, 0xb7, 0xff, 0xbf, 0xef, 0xee, 0x93, 0x0e, 0xf6,
	0xe3, 0x80, 0xae, 0xb1, 0x35, 0xc9, 0xde, 0x91, 0x27, 0x71, 0x1b, 0xfa, 0xe1, 0x0b, 0xd2, 0xef,
	0x01, 0x9d, 0xc2, 0xce, 0xf8, 0x86, 0xac, 0x28, 0x20, 0xad, 0x1d, 0xfd, 0x96, 0x01, 0x96, 0x4d,
	0x95, 0xb3, 0x82, 0x1d, 0x13, 0x05, 0x61, 0x16, 0xf6, 0x3e, 0x2b, 0xf1, 0x04, 0xe0, 0x69, 0xe5,
	0x9b, 0xc8, 0xef, 0x3c, 0xcd, 0xf4, 0xf0, 0x07, 0xa9, 0xa6, 0x16, 0xed, 0xd9, 0x74, 0xc6, 0xfe,
	0xa0, 0x78, 0x04, 0x7e, 0xad, 0xda, 0x8d, 0xb3, 0x46, 0x06, 0x4d, 0x8b, 0xb6, 0xf4, 0x53, 0x8f,
	0x51, 0xb3, 0x7f, 0x7e, 0x90, 0x01, 0xca, 0x28, 0xd0, 0x53, 0x8f, 0x2a, 0xf1, 0x4b, 0x14, 0x39,
	0xf0, 0xcb, 0xec, 0xcc, 0xb7, 0x05, 0x3b, 0x32, 0xb5, 0xd4, 0xd3, 0x09, 0x92, 0xf5, 0x42, 0xdc,
	0x03, 0x7f, 0xc3, 0xda, 0x8c, 0x9d, 0xcf, 0x6e, 0x04, 0x87, 0xed, 0x59, 0xbf, 0x66, 0x2c, 0x84,
	0xf7, 0x0f, 0x9d, 0x6d, 0x2e, 0xbb, 0xf8, 0xfb, 0xcb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xd3, 0x63, 0xfe, 0x0d, 0x01, 0x00, 0x00,
}
