// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/userpb/user.proto

package pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 通过手机号找用户
type FindUserByTelReq struct {
	// 手机号
	Tel                  string   `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByTelReq) Reset()         { *m = FindUserByTelReq{} }
func (m *FindUserByTelReq) String() string { return proto.CompactTextString(m) }
func (*FindUserByTelReq) ProtoMessage()    {}
func (*FindUserByTelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{0}
}
func (m *FindUserByTelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByTelReq.Unmarshal(m, b)
}
func (m *FindUserByTelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByTelReq.Marshal(b, m, deterministic)
}
func (dst *FindUserByTelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByTelReq.Merge(dst, src)
}
func (m *FindUserByTelReq) XXX_Size() int {
	return xxx_messageInfo_FindUserByTelReq.Size(m)
}
func (m *FindUserByTelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByTelReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByTelReq proto.InternalMessageInfo

func (m *FindUserByTelReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

// 返回值，手机号是否存在
type FindUserByTelRes struct {
	// 1.不存在 2.存在
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserByTelRes) Reset()         { *m = FindUserByTelRes{} }
func (m *FindUserByTelRes) String() string { return proto.CompactTextString(m) }
func (*FindUserByTelRes) ProtoMessage()    {}
func (*FindUserByTelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{1}
}
func (m *FindUserByTelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByTelRes.Unmarshal(m, b)
}
func (m *FindUserByTelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByTelRes.Marshal(b, m, deterministic)
}
func (dst *FindUserByTelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByTelRes.Merge(dst, src)
}
func (m *FindUserByTelRes) XXX_Size() int {
	return xxx_messageInfo_FindUserByTelRes.Size(m)
}
func (m *FindUserByTelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByTelRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByTelRes proto.InternalMessageInfo

func (m *FindUserByTelRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 发送验证码
type SendCodeReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 验证码类型  --“register”：注册。”login“：登陆，“findpwd”:找回密码
	CodeTypes            string   `protobuf:"bytes,2,opt,name=CodeTypes,proto3" json:"CodeTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeReq) Reset()         { *m = SendCodeReq{} }
func (m *SendCodeReq) String() string { return proto.CompactTextString(m) }
func (*SendCodeReq) ProtoMessage()    {}
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{2}
}
func (m *SendCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeReq.Unmarshal(m, b)
}
func (m *SendCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeReq.Marshal(b, m, deterministic)
}
func (dst *SendCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeReq.Merge(dst, src)
}
func (m *SendCodeReq) XXX_Size() int {
	return xxx_messageInfo_SendCodeReq.Size(m)
}
func (m *SendCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeReq proto.InternalMessageInfo

func (m *SendCodeReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *SendCodeReq) GetCodeTypes() string {
	if m != nil {
		return m.CodeTypes
	}
	return ""
}

// 注册
type RegisterReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// 验证码
	SmsCode string `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	// 验证码类型 --“register”：注册。”login“：登陆，“findpwd”:找回密码
	CodeTypes string `protobuf:"bytes,4,opt,name=CodeTypes,proto3" json:"CodeTypes,omitempty"`
	// 设备号
	DeviceId string `protobuf:"bytes,5,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	// 公钥
	PublicKey            string   `protobuf:"bytes,6,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{3}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(dst, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

func (m *RegisterReq) GetCodeTypes() string {
	if m != nil {
		return m.CodeTypes
	}
	return ""
}

func (m *RegisterReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *RegisterReq) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

// 验证码登陆
type CodeLoginReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 验证码
	SmsCode string `protobuf:"bytes,2,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	// 验证码类型 --“register”：注册。”login“：登陆，“findpwd”:找回密码
	CodeTypes string `protobuf:"bytes,3,opt,name=CodeTypes,proto3" json:"CodeTypes,omitempty"`
	// 设备号
	DeviceId string `protobuf:"bytes,4,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	// 公钥
	PublicKey            string   `protobuf:"bytes,5,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeLoginReq) Reset()         { *m = CodeLoginReq{} }
func (m *CodeLoginReq) String() string { return proto.CompactTextString(m) }
func (*CodeLoginReq) ProtoMessage()    {}
func (*CodeLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{4}
}
func (m *CodeLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeLoginReq.Unmarshal(m, b)
}
func (m *CodeLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeLoginReq.Marshal(b, m, deterministic)
}
func (dst *CodeLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeLoginReq.Merge(dst, src)
}
func (m *CodeLoginReq) XXX_Size() int {
	return xxx_messageInfo_CodeLoginReq.Size(m)
}
func (m *CodeLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_CodeLoginReq proto.InternalMessageInfo

func (m *CodeLoginReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *CodeLoginReq) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

func (m *CodeLoginReq) GetCodeTypes() string {
	if m != nil {
		return m.CodeTypes
	}
	return ""
}

func (m *CodeLoginReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *CodeLoginReq) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

// 账号密码登陆
type LoginReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// 设备号
	DeviceId string `protobuf:"bytes,3,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	// 公钥
	PublicKey            string   `protobuf:"bytes,4,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{5}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *LoginReq) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

// 找回密码
type FindPasswordReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// 验证码
	SmsCode string `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	// 验证码类型 --“register”：注册。”login“：登陆，“findpwd”:找回密码
	CodeTypes            string   `protobuf:"bytes,4,opt,name=CodeTypes,proto3" json:"CodeTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPasswordReq) Reset()         { *m = FindPasswordReq{} }
func (m *FindPasswordReq) String() string { return proto.CompactTextString(m) }
func (*FindPasswordReq) ProtoMessage()    {}
func (*FindPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{6}
}
func (m *FindPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPasswordReq.Unmarshal(m, b)
}
func (m *FindPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPasswordReq.Marshal(b, m, deterministic)
}
func (dst *FindPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPasswordReq.Merge(dst, src)
}
func (m *FindPasswordReq) XXX_Size() int {
	return xxx_messageInfo_FindPasswordReq.Size(m)
}
func (m *FindPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindPasswordReq proto.InternalMessageInfo

func (m *FindPasswordReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *FindPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FindPasswordReq) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

func (m *FindPasswordReq) GetCodeTypes() string {
	if m != nil {
		return m.CodeTypes
	}
	return ""
}

// 修改密码
type ModifyPwdReq struct {
	// 手机号
	Tel string `protobuf:"bytes,1,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// 验证码
	SmsCode string `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	// 验证码类型 --“register”：注册。”login“：登陆，“findpwd”:找回密码
	CodeTypes            string   `protobuf:"bytes,4,opt,name=CodeTypes,proto3" json:"CodeTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPwdReq) Reset()         { *m = ModifyPwdReq{} }
func (m *ModifyPwdReq) String() string { return proto.CompactTextString(m) }
func (*ModifyPwdReq) ProtoMessage()    {}
func (*ModifyPwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{7}
}
func (m *ModifyPwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPwdReq.Unmarshal(m, b)
}
func (m *ModifyPwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPwdReq.Marshal(b, m, deterministic)
}
func (dst *ModifyPwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPwdReq.Merge(dst, src)
}
func (m *ModifyPwdReq) XXX_Size() int {
	return xxx_messageInfo_ModifyPwdReq.Size(m)
}
func (m *ModifyPwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPwdReq proto.InternalMessageInfo

func (m *ModifyPwdReq) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *ModifyPwdReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ModifyPwdReq) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

func (m *ModifyPwdReq) GetCodeTypes() string {
	if m != nil {
		return m.CodeTypes
	}
	return ""
}

// 编辑用户
type EditUserReq struct {
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	// 头像
	Pic string `protobuf:"bytes,3,opt,name=Pic,proto3" json:"Pic,omitempty"`
	// 性别
	Gender int32 `protobuf:"varint,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	// 地址
	AddressId string `protobuf:"bytes,5,opt,name=AddressId,proto3" json:"AddressId,omitempty"`
	// 生日
	Birthday             string   `protobuf:"bytes,6,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserReq) Reset()         { *m = EditUserReq{} }
func (m *EditUserReq) String() string { return proto.CompactTextString(m) }
func (*EditUserReq) ProtoMessage()    {}
func (*EditUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{8}
}
func (m *EditUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserReq.Unmarshal(m, b)
}
func (m *EditUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserReq.Marshal(b, m, deterministic)
}
func (dst *EditUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserReq.Merge(dst, src)
}
func (m *EditUserReq) XXX_Size() int {
	return xxx_messageInfo_EditUserReq.Size(m)
}
func (m *EditUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserReq proto.InternalMessageInfo

func (m *EditUserReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EditUserReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *EditUserReq) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *EditUserReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *EditUserReq) GetAddressId() string {
	if m != nil {
		return m.AddressId
	}
	return ""
}

func (m *EditUserReq) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

// 启用禁用
type ModifyStatusReq struct {
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 状态 1.启用 2.禁用
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyStatusReq) Reset()         { *m = ModifyStatusReq{} }
func (m *ModifyStatusReq) String() string { return proto.CompactTextString(m) }
func (*ModifyStatusReq) ProtoMessage()    {}
func (*ModifyStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{9}
}
func (m *ModifyStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyStatusReq.Unmarshal(m, b)
}
func (m *ModifyStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyStatusReq.Marshal(b, m, deterministic)
}
func (dst *ModifyStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyStatusReq.Merge(dst, src)
}
func (m *ModifyStatusReq) XXX_Size() int {
	return xxx_messageInfo_ModifyStatusReq.Size(m)
}
func (m *ModifyStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyStatusReq proto.InternalMessageInfo

func (m *ModifyStatusReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ModifyStatusReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 用户分页列表
type UserListReq struct {
	// 第几页
	Index int32 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	// 每页条数
	Length               int32    `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{10}
}
func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (dst *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(dst, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UserListReq) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

// 用户分页列表返回值
type UserListRes struct {
	// 用户列表
	UserList             []*User  `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRes) Reset()         { *m = UserListRes{} }
func (m *UserListRes) String() string { return proto.CompactTextString(m) }
func (*UserListRes) ProtoMessage()    {}
func (*UserListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{11}
}
func (m *UserListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRes.Unmarshal(m, b)
}
func (m *UserListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRes.Marshal(b, m, deterministic)
}
func (dst *UserListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRes.Merge(dst, src)
}
func (m *UserListRes) XXX_Size() int {
	return xxx_messageInfo_UserListRes.Size(m)
}
func (m *UserListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRes proto.InternalMessageInfo

func (m *UserListRes) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

// 用户实体
type User struct {
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 哈希id
	HashId string `protobuf:"bytes,2,opt,name=HashId,proto3" json:"HashId,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	// 头像
	Pic string `protobuf:"bytes,4,opt,name=Pic,proto3" json:"Pic,omitempty"`
	// 实名认证 0.未认证 1.认证中 2.认证成功 3.认证失败
	Identify int32 `protobuf:"varint,5,opt,name=Identify,proto3" json:"Identify,omitempty"`
	// vip名称
	VipName string `protobuf:"bytes,6,opt,name=VipName,proto3" json:"VipName,omitempty"`
	// 性别 1.男 2.女
	Gender int32 `protobuf:"varint,7,opt,name=Gender,proto3" json:"Gender,omitempty"`
	// 标签
	Badge string `protobuf:"bytes,8,opt,name=Badge,proto3" json:"Badge,omitempty"`
	// 地址id
	AddressId string `protobuf:"bytes,9,opt,name=AddressId,proto3" json:"AddressId,omitempty"`
	// 手机号
	Tel string `protobuf:"bytes,10,opt,name=Tel,proto3" json:"Tel,omitempty"`
	// 生日
	Birthday string `protobuf:"bytes,11,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	// 状态 1.正常 2.冻结
	Status               int32    `protobuf:"varint,12,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{12}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *User) GetIdentify() int32 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *User) GetVipName() string {
	if m != nil {
		return m.VipName
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetBadge() string {
	if m != nil {
		return m.Badge
	}
	return ""
}

func (m *User) GetAddressId() string {
	if m != nil {
		return m.AddressId
	}
	return ""
}

func (m *User) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 关注
type FocusUserReq struct {
	// 关注人
	FromId int64 `protobuf:"varint,1,opt,name=FromId,proto3" json:"FromId,omitempty"`
	// 被关注人
	ToId                 int64    `protobuf:"varint,2,opt,name=ToId,proto3" json:"ToId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FocusUserReq) Reset()         { *m = FocusUserReq{} }
func (m *FocusUserReq) String() string { return proto.CompactTextString(m) }
func (*FocusUserReq) ProtoMessage()    {}
func (*FocusUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{13}
}
func (m *FocusUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FocusUserReq.Unmarshal(m, b)
}
func (m *FocusUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FocusUserReq.Marshal(b, m, deterministic)
}
func (dst *FocusUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FocusUserReq.Merge(dst, src)
}
func (m *FocusUserReq) XXX_Size() int {
	return xxx_messageInfo_FocusUserReq.Size(m)
}
func (m *FocusUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FocusUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_FocusUserReq proto.InternalMessageInfo

func (m *FocusUserReq) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *FocusUserReq) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

// 取消关注
type UnFocusUserReq struct {
	// 关注人
	FromId int64 `protobuf:"varint,1,opt,name=FromId,proto3" json:"FromId,omitempty"`
	// 被关注人
	ToId                 int64    `protobuf:"varint,2,opt,name=ToId,proto3" json:"ToId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFocusUserReq) Reset()         { *m = UnFocusUserReq{} }
func (m *UnFocusUserReq) String() string { return proto.CompactTextString(m) }
func (*UnFocusUserReq) ProtoMessage()    {}
func (*UnFocusUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{14}
}
func (m *UnFocusUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFocusUserReq.Unmarshal(m, b)
}
func (m *UnFocusUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFocusUserReq.Marshal(b, m, deterministic)
}
func (dst *UnFocusUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFocusUserReq.Merge(dst, src)
}
func (m *UnFocusUserReq) XXX_Size() int {
	return xxx_messageInfo_UnFocusUserReq.Size(m)
}
func (m *UnFocusUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFocusUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnFocusUserReq proto.InternalMessageInfo

func (m *UnFocusUserReq) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *UnFocusUserReq) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

// 添加联系人
type AddFriendReq struct {
	// 用户1
	User1Id int64 `protobuf:"varint,1,opt,name=User1Id,proto3" json:"User1Id,omitempty"`
	// 用户2
	User2Id              int64    `protobuf:"varint,2,opt,name=User2Id,proto3" json:"User2Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendReq) Reset()         { *m = AddFriendReq{} }
func (m *AddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AddFriendReq) ProtoMessage()    {}
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{15}
}
func (m *AddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendReq.Unmarshal(m, b)
}
func (m *AddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendReq.Marshal(b, m, deterministic)
}
func (dst *AddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendReq.Merge(dst, src)
}
func (m *AddFriendReq) XXX_Size() int {
	return xxx_messageInfo_AddFriendReq.Size(m)
}
func (m *AddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendReq proto.InternalMessageInfo

func (m *AddFriendReq) GetUser1Id() int64 {
	if m != nil {
		return m.User1Id
	}
	return 0
}

func (m *AddFriendReq) GetUser2Id() int64 {
	if m != nil {
		return m.User2Id
	}
	return 0
}

// 删除联系人
type DelFriendReq struct {
	// 用户1
	User1Id int64 `protobuf:"varint,1,opt,name=User1Id,proto3" json:"User1Id,omitempty"`
	// 用户2
	User2Id              int64    `protobuf:"varint,2,opt,name=User2Id,proto3" json:"User2Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFriendReq) Reset()         { *m = DelFriendReq{} }
func (m *DelFriendReq) String() string { return proto.CompactTextString(m) }
func (*DelFriendReq) ProtoMessage()    {}
func (*DelFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{16}
}
func (m *DelFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFriendReq.Unmarshal(m, b)
}
func (m *DelFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFriendReq.Marshal(b, m, deterministic)
}
func (dst *DelFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFriendReq.Merge(dst, src)
}
func (m *DelFriendReq) XXX_Size() int {
	return xxx_messageInfo_DelFriendReq.Size(m)
}
func (m *DelFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelFriendReq proto.InternalMessageInfo

func (m *DelFriendReq) GetUser1Id() int64 {
	if m != nil {
		return m.User1Id
	}
	return 0
}

func (m *DelFriendReq) GetUser2Id() int64 {
	if m != nil {
		return m.User2Id
	}
	return 0
}

// 加入黑名单
type BlockUserReq struct {
	// 拉黑用户
	FromId int64 `protobuf:"varint,1,opt,name=FromId,proto3" json:"FromId,omitempty"`
	// 被拉黑用户
	ToId                 int64    `protobuf:"varint,2,opt,name=ToId,proto3" json:"ToId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockUserReq) Reset()         { *m = BlockUserReq{} }
func (m *BlockUserReq) String() string { return proto.CompactTextString(m) }
func (*BlockUserReq) ProtoMessage()    {}
func (*BlockUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{17}
}
func (m *BlockUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockUserReq.Unmarshal(m, b)
}
func (m *BlockUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockUserReq.Marshal(b, m, deterministic)
}
func (dst *BlockUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockUserReq.Merge(dst, src)
}
func (m *BlockUserReq) XXX_Size() int {
	return xxx_messageInfo_BlockUserReq.Size(m)
}
func (m *BlockUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlockUserReq proto.InternalMessageInfo

func (m *BlockUserReq) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *BlockUserReq) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

// 移除黑名单
type UnblockUserReq struct {
	// 拉黑用户
	FromId int64 `protobuf:"varint,1,opt,name=FromId,proto3" json:"FromId,omitempty"`
	// 被拉黑用户
	ToId                 int64    `protobuf:"varint,2,opt,name=ToId,proto3" json:"ToId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnblockUserReq) Reset()         { *m = UnblockUserReq{} }
func (m *UnblockUserReq) String() string { return proto.CompactTextString(m) }
func (*UnblockUserReq) ProtoMessage()    {}
func (*UnblockUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{18}
}
func (m *UnblockUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnblockUserReq.Unmarshal(m, b)
}
func (m *UnblockUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnblockUserReq.Marshal(b, m, deterministic)
}
func (dst *UnblockUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnblockUserReq.Merge(dst, src)
}
func (m *UnblockUserReq) XXX_Size() int {
	return xxx_messageInfo_UnblockUserReq.Size(m)
}
func (m *UnblockUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnblockUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnblockUserReq proto.InternalMessageInfo

func (m *UnblockUserReq) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *UnblockUserReq) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

// 用户卡包列表
type UserCardListReq struct {
	// 用户id
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCardListReq) Reset()         { *m = UserCardListReq{} }
func (m *UserCardListReq) String() string { return proto.CompactTextString(m) }
func (*UserCardListReq) ProtoMessage()    {}
func (*UserCardListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{19}
}
func (m *UserCardListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCardListReq.Unmarshal(m, b)
}
func (m *UserCardListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCardListReq.Marshal(b, m, deterministic)
}
func (dst *UserCardListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCardListReq.Merge(dst, src)
}
func (m *UserCardListReq) XXX_Size() int {
	return xxx_messageInfo_UserCardListReq.Size(m)
}
func (m *UserCardListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCardListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCardListReq proto.InternalMessageInfo

func (m *UserCardListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 用户卡包列表--返回值
type UserCardListRes struct {
	// 卡列表
	CardList             []*UserCard `protobuf:"bytes,1,rep,name=CardList,proto3" json:"CardList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserCardListRes) Reset()         { *m = UserCardListRes{} }
func (m *UserCardListRes) String() string { return proto.CompactTextString(m) }
func (*UserCardListRes) ProtoMessage()    {}
func (*UserCardListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{20}
}
func (m *UserCardListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCardListRes.Unmarshal(m, b)
}
func (m *UserCardListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCardListRes.Marshal(b, m, deterministic)
}
func (dst *UserCardListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCardListRes.Merge(dst, src)
}
func (m *UserCardListRes) XXX_Size() int {
	return xxx_messageInfo_UserCardListRes.Size(m)
}
func (m *UserCardListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCardListRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserCardListRes proto.InternalMessageInfo

func (m *UserCardListRes) GetCardList() []*UserCard {
	if m != nil {
		return m.CardList
	}
	return nil
}

// 暴击卡实体
type UserCard struct {
	// 卡id
	CardId int64 `protobuf:"varint,1,opt,name=CardId,proto3" json:"CardId,omitempty"`
	// 卡类型
	CardType string `protobuf:"bytes,2,opt,name=CardType,proto3" json:"CardType,omitempty"`
	// 卡名称
	CardName string `protobuf:"bytes,3,opt,name=CardName,proto3" json:"CardName,omitempty"`
	// 暴击倍数
	Times                int64    `protobuf:"varint,5,opt,name=times,proto3" json:"times,omitempty"`
	UserCardId           int64    `protobuf:"varint,6,opt,name=UserCardId,proto3" json:"UserCardId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCard) Reset()         { *m = UserCard{} }
func (m *UserCard) String() string { return proto.CompactTextString(m) }
func (*UserCard) ProtoMessage()    {}
func (*UserCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{21}
}
func (m *UserCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCard.Unmarshal(m, b)
}
func (m *UserCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCard.Marshal(b, m, deterministic)
}
func (dst *UserCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCard.Merge(dst, src)
}
func (m *UserCard) XXX_Size() int {
	return xxx_messageInfo_UserCard.Size(m)
}
func (m *UserCard) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCard.DiscardUnknown(m)
}

var xxx_messageInfo_UserCard proto.InternalMessageInfo

func (m *UserCard) GetCardId() int64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *UserCard) GetCardType() string {
	if m != nil {
		return m.CardType
	}
	return ""
}

func (m *UserCard) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *UserCard) GetTimes() int64 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *UserCard) GetUserCardId() int64 {
	if m != nil {
		return m.UserCardId
	}
	return 0
}

// 使用卡
type UseCardReq struct {
	// 用户暴击卡id
	UserCardId           int64    `protobuf:"varint,1,opt,name=UserCardId,proto3" json:"UserCardId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseCardReq) Reset()         { *m = UseCardReq{} }
func (m *UseCardReq) String() string { return proto.CompactTextString(m) }
func (*UseCardReq) ProtoMessage()    {}
func (*UseCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{22}
}
func (m *UseCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseCardReq.Unmarshal(m, b)
}
func (m *UseCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseCardReq.Marshal(b, m, deterministic)
}
func (dst *UseCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseCardReq.Merge(dst, src)
}
func (m *UseCardReq) XXX_Size() int {
	return xxx_messageInfo_UseCardReq.Size(m)
}
func (m *UseCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UseCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_UseCardReq proto.InternalMessageInfo

func (m *UseCardReq) GetUserCardId() int64 {
	if m != nil {
		return m.UserCardId
	}
	return 0
}

// 发送卡
type SendCardReq struct {
	// 用户暴击卡id
	UserCardId int64 `protobuf:"varint,1,opt,name=UserCardId,proto3" json:"UserCardId,omitempty"`
	// 用户id
	UserId int64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 接收人或者群id
	ReciveId             string   `protobuf:"bytes,3,opt,name=ReciveId,proto3" json:"ReciveId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCardReq) Reset()         { *m = SendCardReq{} }
func (m *SendCardReq) String() string { return proto.CompactTextString(m) }
func (*SendCardReq) ProtoMessage()    {}
func (*SendCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{23}
}
func (m *SendCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCardReq.Unmarshal(m, b)
}
func (m *SendCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCardReq.Marshal(b, m, deterministic)
}
func (dst *SendCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCardReq.Merge(dst, src)
}
func (m *SendCardReq) XXX_Size() int {
	return xxx_messageInfo_SendCardReq.Size(m)
}
func (m *SendCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendCardReq proto.InternalMessageInfo

func (m *SendCardReq) GetUserCardId() int64 {
	if m != nil {
		return m.UserCardId
	}
	return 0
}

func (m *SendCardReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SendCardReq) GetReciveId() string {
	if m != nil {
		return m.ReciveId
	}
	return ""
}

// 接收卡
type ReciveCardReq struct {
	// 用户暴击卡id
	UserCardId int64 `protobuf:"varint,1,opt,name=UserCardId,proto3" json:"UserCardId,omitempty"`
	// 用户id
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReciveCardReq) Reset()         { *m = ReciveCardReq{} }
func (m *ReciveCardReq) String() string { return proto.CompactTextString(m) }
func (*ReciveCardReq) ProtoMessage()    {}
func (*ReciveCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{24}
}
func (m *ReciveCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReciveCardReq.Unmarshal(m, b)
}
func (m *ReciveCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReciveCardReq.Marshal(b, m, deterministic)
}
func (dst *ReciveCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReciveCardReq.Merge(dst, src)
}
func (m *ReciveCardReq) XXX_Size() int {
	return xxx_messageInfo_ReciveCardReq.Size(m)
}
func (m *ReciveCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReciveCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReciveCardReq proto.InternalMessageInfo

func (m *ReciveCardReq) GetUserCardId() int64 {
	if m != nil {
		return m.UserCardId
	}
	return 0
}

func (m *ReciveCardReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CardListRes struct {
	// 暴击卡列表
	CardList             []*Card  `protobuf:"bytes,1,rep,name=CardList,proto3" json:"CardList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardListRes) Reset()         { *m = CardListRes{} }
func (m *CardListRes) String() string { return proto.CompactTextString(m) }
func (*CardListRes) ProtoMessage()    {}
func (*CardListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{25}
}
func (m *CardListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardListRes.Unmarshal(m, b)
}
func (m *CardListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardListRes.Marshal(b, m, deterministic)
}
func (dst *CardListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardListRes.Merge(dst, src)
}
func (m *CardListRes) XXX_Size() int {
	return xxx_messageInfo_CardListRes.Size(m)
}
func (m *CardListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CardListRes.DiscardUnknown(m)
}

var xxx_messageInfo_CardListRes proto.InternalMessageInfo

func (m *CardListRes) GetCardList() []*Card {
	if m != nil {
		return m.CardList
	}
	return nil
}

// 暴击卡实体
type Card struct {
	// 卡id
	CardId int64 `protobuf:"varint,1,opt,name=CardId,proto3" json:"CardId,omitempty"`
	// 卡类型
	CardType string `protobuf:"bytes,2,opt,name=CardType,proto3" json:"CardType,omitempty"`
	// 卡名称
	CardName string `protobuf:"bytes,3,opt,name=CardName,proto3" json:"CardName,omitempty"`
	// 备注
	Note string `protobuf:"bytes,4,opt,name=Note,proto3" json:"Note,omitempty"`
	// 暴击倍数
	Times                int64    `protobuf:"varint,5,opt,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{26}
}
func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (dst *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(dst, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetCardId() int64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *Card) GetCardType() string {
	if m != nil {
		return m.CardType
	}
	return ""
}

func (m *Card) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *Card) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Card) GetTimes() int64 {
	if m != nil {
		return m.Times
	}
	return 0
}

// 添加暴击卡
type AddCardReq struct {
	// 卡类型
	CardType string `protobuf:"bytes,1,opt,name=CardType,proto3" json:"CardType,omitempty"`
	// 卡名称
	CardName string `protobuf:"bytes,2,opt,name=CardName,proto3" json:"CardName,omitempty"`
	// 暴击倍数
	Times int64 `protobuf:"varint,3,opt,name=Times,proto3" json:"Times,omitempty"`
	// 备注
	Note                 string   `protobuf:"bytes,4,opt,name=Note,proto3" json:"Note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCardReq) Reset()         { *m = AddCardReq{} }
func (m *AddCardReq) String() string { return proto.CompactTextString(m) }
func (*AddCardReq) ProtoMessage()    {}
func (*AddCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{27}
}
func (m *AddCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCardReq.Unmarshal(m, b)
}
func (m *AddCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCardReq.Marshal(b, m, deterministic)
}
func (dst *AddCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCardReq.Merge(dst, src)
}
func (m *AddCardReq) XXX_Size() int {
	return xxx_messageInfo_AddCardReq.Size(m)
}
func (m *AddCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddCardReq proto.InternalMessageInfo

func (m *AddCardReq) GetCardType() string {
	if m != nil {
		return m.CardType
	}
	return ""
}

func (m *AddCardReq) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *AddCardReq) GetTimes() int64 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *AddCardReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 编辑暴击卡
type EditCardReq struct {
	// 卡id
	CardId int64 `protobuf:"varint,1,opt,name=CardId,proto3" json:"CardId,omitempty"`
	// 卡名称
	CardName string `protobuf:"bytes,2,opt,name=CardName,proto3" json:"CardName,omitempty"`
	// 备注
	Note                 string   `protobuf:"bytes,3,opt,name=Note,proto3" json:"Note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCardReq) Reset()         { *m = EditCardReq{} }
func (m *EditCardReq) String() string { return proto.CompactTextString(m) }
func (*EditCardReq) ProtoMessage()    {}
func (*EditCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{28}
}
func (m *EditCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCardReq.Unmarshal(m, b)
}
func (m *EditCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCardReq.Marshal(b, m, deterministic)
}
func (dst *EditCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCardReq.Merge(dst, src)
}
func (m *EditCardReq) XXX_Size() int {
	return xxx_messageInfo_EditCardReq.Size(m)
}
func (m *EditCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditCardReq proto.InternalMessageInfo

func (m *EditCardReq) GetCardId() int64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *EditCardReq) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *EditCardReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 标签列表--返回值
type TagListRes struct {
	// 标签列表
	TagList              []*Tag   `protobuf:"bytes,1,rep,name=TagList,proto3" json:"TagList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagListRes) Reset()         { *m = TagListRes{} }
func (m *TagListRes) String() string { return proto.CompactTextString(m) }
func (*TagListRes) ProtoMessage()    {}
func (*TagListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{29}
}
func (m *TagListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagListRes.Unmarshal(m, b)
}
func (m *TagListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagListRes.Marshal(b, m, deterministic)
}
func (dst *TagListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagListRes.Merge(dst, src)
}
func (m *TagListRes) XXX_Size() int {
	return xxx_messageInfo_TagListRes.Size(m)
}
func (m *TagListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TagListRes.DiscardUnknown(m)
}

var xxx_messageInfo_TagListRes proto.InternalMessageInfo

func (m *TagListRes) GetTagList() []*Tag {
	if m != nil {
		return m.TagList
	}
	return nil
}

// 标签实体
type Tag struct {
	// 标签名称
	TagName string `protobuf:"bytes,1,opt,name=TagName,proto3" json:"TagName,omitempty"`
	// 标签id
	TagId                int64    `protobuf:"varint,2,opt,name=TagId,proto3" json:"TagId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{30}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func (m *Tag) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

// 添加标签
type AddTagReq struct {
	// 标签名称
	TagName              string   `protobuf:"bytes,1,opt,name=TagName,proto3" json:"TagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagReq) Reset()         { *m = AddTagReq{} }
func (m *AddTagReq) String() string { return proto.CompactTextString(m) }
func (*AddTagReq) ProtoMessage()    {}
func (*AddTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{31}
}
func (m *AddTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagReq.Unmarshal(m, b)
}
func (m *AddTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagReq.Marshal(b, m, deterministic)
}
func (dst *AddTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagReq.Merge(dst, src)
}
func (m *AddTagReq) XXX_Size() int {
	return xxx_messageInfo_AddTagReq.Size(m)
}
func (m *AddTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagReq proto.InternalMessageInfo

func (m *AddTagReq) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

// 编辑标签
type EditTagReq struct {
	// 标签id
	TagId int64 `protobuf:"varint,1,opt,name=TagId,proto3" json:"TagId,omitempty"`
	// 标签名称
	TagName              string   `protobuf:"bytes,2,opt,name=TagName,proto3" json:"TagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditTagReq) Reset()         { *m = EditTagReq{} }
func (m *EditTagReq) String() string { return proto.CompactTextString(m) }
func (*EditTagReq) ProtoMessage()    {}
func (*EditTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{32}
}
func (m *EditTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditTagReq.Unmarshal(m, b)
}
func (m *EditTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditTagReq.Marshal(b, m, deterministic)
}
func (dst *EditTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditTagReq.Merge(dst, src)
}
func (m *EditTagReq) XXX_Size() int {
	return xxx_messageInfo_EditTagReq.Size(m)
}
func (m *EditTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditTagReq proto.InternalMessageInfo

func (m *EditTagReq) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *EditTagReq) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

// 删除标签
type DelTagReq struct {
	// 标签id
	TagId                int64    `protobuf:"varint,1,opt,name=TagId,proto3" json:"TagId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTagReq) Reset()         { *m = DelTagReq{} }
func (m *DelTagReq) String() string { return proto.CompactTextString(m) }
func (*DelTagReq) ProtoMessage()    {}
func (*DelTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{33}
}
func (m *DelTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTagReq.Unmarshal(m, b)
}
func (m *DelTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTagReq.Marshal(b, m, deterministic)
}
func (dst *DelTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTagReq.Merge(dst, src)
}
func (m *DelTagReq) XXX_Size() int {
	return xxx_messageInfo_DelTagReq.Size(m)
}
func (m *DelTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelTagReq proto.InternalMessageInfo

func (m *DelTagReq) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

// 编辑用户标签
type UpdateUserTagReq struct {
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 标签列表
	TagList              []*Tag   `protobuf:"bytes,2,rep,name=TagList,proto3" json:"TagList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserTagReq) Reset()         { *m = UpdateUserTagReq{} }
func (m *UpdateUserTagReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserTagReq) ProtoMessage()    {}
func (*UpdateUserTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{34}
}
func (m *UpdateUserTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserTagReq.Unmarshal(m, b)
}
func (m *UpdateUserTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserTagReq.Marshal(b, m, deterministic)
}
func (dst *UpdateUserTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserTagReq.Merge(dst, src)
}
func (m *UpdateUserTagReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserTagReq.Size(m)
}
func (m *UpdateUserTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserTagReq proto.InternalMessageInfo

func (m *UpdateUserTagReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserTagReq) GetTagList() []*Tag {
	if m != nil {
		return m.TagList
	}
	return nil
}

// 用户标签列表
type UserTagListReq struct {
	// 用户id
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTagListReq) Reset()         { *m = UserTagListReq{} }
func (m *UserTagListReq) String() string { return proto.CompactTextString(m) }
func (*UserTagListReq) ProtoMessage()    {}
func (*UserTagListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{35}
}
func (m *UserTagListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTagListReq.Unmarshal(m, b)
}
func (m *UserTagListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTagListReq.Marshal(b, m, deterministic)
}
func (dst *UserTagListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTagListReq.Merge(dst, src)
}
func (m *UserTagListReq) XXX_Size() int {
	return xxx_messageInfo_UserTagListReq.Size(m)
}
func (m *UserTagListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTagListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserTagListReq proto.InternalMessageInfo

func (m *UserTagListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 用户标签列表 -- 返回值
type UserTagListRes struct {
	// 标签列表
	TagList              []*Tag   `protobuf:"bytes,1,rep,name=TagList,proto3" json:"TagList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTagListRes) Reset()         { *m = UserTagListRes{} }
func (m *UserTagListRes) String() string { return proto.CompactTextString(m) }
func (*UserTagListRes) ProtoMessage()    {}
func (*UserTagListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b7a40df86b403cc9, []int{36}
}
func (m *UserTagListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTagListRes.Unmarshal(m, b)
}
func (m *UserTagListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTagListRes.Marshal(b, m, deterministic)
}
func (dst *UserTagListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTagListRes.Merge(dst, src)
}
func (m *UserTagListRes) XXX_Size() int {
	return xxx_messageInfo_UserTagListRes.Size(m)
}
func (m *UserTagListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTagListRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserTagListRes proto.InternalMessageInfo

func (m *UserTagListRes) GetTagList() []*Tag {
	if m != nil {
		return m.TagList
	}
	return nil
}

func init() {
	proto.RegisterType((*FindUserByTelReq)(nil), "userpb.FindUserByTelReq")
	proto.RegisterType((*FindUserByTelRes)(nil), "userpb.FindUserByTelRes")
	proto.RegisterType((*SendCodeReq)(nil), "userpb.SendCodeReq")
	proto.RegisterType((*RegisterReq)(nil), "userpb.RegisterReq")
	proto.RegisterType((*CodeLoginReq)(nil), "userpb.CodeLoginReq")
	proto.RegisterType((*LoginReq)(nil), "userpb.LoginReq")
	proto.RegisterType((*FindPasswordReq)(nil), "userpb.FindPasswordReq")
	proto.RegisterType((*ModifyPwdReq)(nil), "userpb.ModifyPwdReq")
	proto.RegisterType((*EditUserReq)(nil), "userpb.EditUserReq")
	proto.RegisterType((*ModifyStatusReq)(nil), "userpb.ModifyStatusReq")
	proto.RegisterType((*UserListReq)(nil), "userpb.UserListReq")
	proto.RegisterType((*UserListRes)(nil), "userpb.UserListRes")
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*FocusUserReq)(nil), "userpb.FocusUserReq")
	proto.RegisterType((*UnFocusUserReq)(nil), "userpb.UnFocusUserReq")
	proto.RegisterType((*AddFriendReq)(nil), "userpb.AddFriendReq")
	proto.RegisterType((*DelFriendReq)(nil), "userpb.DelFriendReq")
	proto.RegisterType((*BlockUserReq)(nil), "userpb.BlockUserReq")
	proto.RegisterType((*UnblockUserReq)(nil), "userpb.UnblockUserReq")
	proto.RegisterType((*UserCardListReq)(nil), "userpb.UserCardListReq")
	proto.RegisterType((*UserCardListRes)(nil), "userpb.UserCardListRes")
	proto.RegisterType((*UserCard)(nil), "userpb.userCard")
	proto.RegisterType((*UseCardReq)(nil), "userpb.UseCardReq")
	proto.RegisterType((*SendCardReq)(nil), "userpb.SendCardReq")
	proto.RegisterType((*ReciveCardReq)(nil), "userpb.ReciveCardReq")
	proto.RegisterType((*CardListRes)(nil), "userpb.CardListRes")
	proto.RegisterType((*Card)(nil), "userpb.card")
	proto.RegisterType((*AddCardReq)(nil), "userpb.AddCardReq")
	proto.RegisterType((*EditCardReq)(nil), "userpb.EditCardReq")
	proto.RegisterType((*TagListRes)(nil), "userpb.TagListRes")
	proto.RegisterType((*Tag)(nil), "userpb.tag")
	proto.RegisterType((*AddTagReq)(nil), "userpb.AddTagReq")
	proto.RegisterType((*EditTagReq)(nil), "userpb.EditTagReq")
	proto.RegisterType((*DelTagReq)(nil), "userpb.DelTagReq")
	proto.RegisterType((*UpdateUserTagReq)(nil), "userpb.UpdateUserTagReq")
	proto.RegisterType((*UserTagListReq)(nil), "userpb.UserTagListReq")
	proto.RegisterType((*UserTagListRes)(nil), "userpb.UserTagListRes")
}

func init() { proto.RegisterFile("pb/userpb/user.proto", fileDescriptor_user_b7a40df86b403cc9) }

var fileDescriptor_user_b7a40df86b403cc9 = []byte{
	// 914 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x6d, 0x6f, 0xdc, 0x44,
	0x10, 0x96, 0x5f, 0xee, 0x72, 0x99, 0x3b, 0x9a, 0xc8, 0x8a, 0x2a, 0xab, 0x42, 0xa8, 0xac, 0xa8,
	0x74, 0xa0, 0x2a, 0x88, 0x56, 0xa8, 0x52, 0x29, 0x42, 0xb9, 0x86, 0x94, 0x13, 0x21, 0x0a, 0x8e,
	0xc3, 0x77, 0xc7, 0xbb, 0x75, 0x56, 0xbd, 0xd8, 0x57, 0xaf, 0xaf, 0x21, 0xdf, 0xf8, 0x09, 0x88,
	0xff, 0xc0, 0x37, 0xf8, 0x8f, 0x68, 0xf6, 0xc5, 0xb7, 0xf6, 0xb9, 0x6e, 0x95, 0x8a, 0x7e, 0xca,
	0x3e, 0xbb, 0x33, 0xf3, 0x8c, 0xe7, 0x99, 0x99, 0x6b, 0x61, 0x6f, 0x79, 0xf1, 0xf5, 0x4a, 0xb0,
	0x52, 0xff, 0xd9, 0x5f, 0x96, 0x45, 0x55, 0x04, 0x43, 0x75, 0x45, 0xbe, 0x80, 0xdd, 0x23, 0x9e,
	0xd3, 0x73, 0xc1, 0xca, 0xd9, 0x4d, 0xcc, 0x16, 0x11, 0x7b, 0x1d, 0xec, 0x82, 0x17, 0xb3, 0x45,
	0xe8, 0xdc, 0x77, 0xa6, 0xdb, 0x11, 0x1e, 0xc9, 0x57, 0x1b, 0x56, 0x22, 0xb8, 0x0b, 0xc3, 0xb3,
	0x2a, 0xa9, 0x56, 0x42, 0x1a, 0x0e, 0x22, 0x8d, 0xc8, 0xf7, 0x30, 0x3e, 0x63, 0x39, 0x7d, 0x5e,
	0x50, 0xd6, 0x19, 0x2c, 0xf8, 0x14, 0xb6, 0xf1, 0x31, 0xbe, 0x59, 0x32, 0x11, 0xba, 0xf2, 0x7e,
	0x7d, 0x41, 0xfe, 0x75, 0x60, 0x1c, 0xb1, 0x8c, 0x8b, 0x8a, 0x95, 0xdd, 0xfe, 0xf7, 0x60, 0x74,
	0x9a, 0x08, 0x71, 0x5d, 0x94, 0x54, 0xbb, 0xd7, 0x38, 0x08, 0x61, 0xeb, 0xec, 0x4a, 0x60, 0xb4,
	0xd0, 0x93, 0x4f, 0x06, 0x36, 0x59, 0xfd, 0x16, 0x2b, 0xc6, 0x3c, 0x64, 0x6f, 0x78, 0xca, 0xe6,
	0x34, 0x1c, 0xa8, 0x98, 0x06, 0xa3, 0xe7, 0xe9, 0xea, 0x62, 0xc1, 0xd3, 0x9f, 0xd9, 0x4d, 0x38,
	0x54, 0x9e, 0xf5, 0x05, 0xf9, 0xcb, 0x81, 0x09, 0xc6, 0x39, 0x2e, 0x32, 0x9e, 0x77, 0x27, 0x6c,
	0x25, 0xe5, 0xf6, 0x24, 0xe5, 0xf5, 0x25, 0xe5, 0xf7, 0x25, 0x35, 0x68, 0x27, 0x55, 0xc2, 0xa8,
	0x27, 0x9f, 0xbe, 0x02, 0xda, 0x9c, 0x5e, 0x1f, 0xa7, 0xdf, 0xe6, 0xbc, 0x86, 0x1d, 0xec, 0x11,
	0x13, 0xe9, 0xa3, 0x69, 0x47, 0x2a, 0x98, 0xfc, 0x52, 0x50, 0xfe, 0xf2, 0xe6, 0xf4, 0xfa, 0x23,
	0xb2, 0xfe, 0xed, 0xc0, 0xf8, 0x47, 0xca, 0x2b, 0x9c, 0x09, 0x64, 0xbd, 0x0b, 0x43, 0x3c, 0xce,
	0xa9, 0x24, 0xf6, 0x22, 0x8d, 0x90, 0xfb, 0x84, 0xa7, 0xaf, 0x4e, 0x92, 0x2b, 0xa3, 0x7e, 0x8d,
	0x31, 0xd3, 0x53, 0x9e, 0x6a, 0x5e, 0x3c, 0x62, 0x94, 0x17, 0x2c, 0xa7, 0xac, 0x94, 0x84, 0x83,
	0x48, 0x23, 0xcc, 0xe5, 0x80, 0xd2, 0x92, 0x09, 0x51, 0x37, 0xe8, 0xfa, 0x02, 0x39, 0x66, 0xbc,
	0xac, 0x2e, 0x69, 0x62, 0x1a, 0xb4, 0xc6, 0xe4, 0x00, 0x76, 0x54, 0x75, 0xd4, 0x78, 0xf6, 0xa5,
	0xba, 0x9e, 0x68, 0xb7, 0x31, 0xd1, 0xdf, 0xc1, 0x18, 0x2d, 0x8e, 0xb9, 0xa8, 0xd0, 0x7d, 0x0f,
	0x06, 0xf3, 0x9c, 0xb2, 0xdf, 0xf5, 0xdc, 0x2b, 0x80, 0xce, 0xc7, 0x2c, 0xcf, 0xaa, 0x4b, 0xe3,
	0xac, 0x10, 0x79, 0x62, 0x3b, 0x8b, 0x60, 0x0a, 0x23, 0x03, 0x43, 0xe7, 0xbe, 0x37, 0x1d, 0x3f,
	0x9a, 0xec, 0xab, 0x55, 0xb4, 0x2f, 0x2b, 0x59, 0xbf, 0x92, 0x7f, 0x5c, 0xf0, 0x11, 0xf4, 0xa5,
	0xfb, 0x53, 0x22, 0x2e, 0xe7, 0x46, 0x53, 0x8d, 0x1a, 0x15, 0xf7, 0xba, 0x2b, 0xee, 0xaf, 0x2b,
	0x7e, 0x0f, 0x46, 0x73, 0xca, 0xf2, 0x8a, 0xbf, 0x54, 0x73, 0x34, 0x88, 0x6a, 0x8c, 0xbd, 0xf1,
	0x1b, 0x5f, 0xca, 0x40, 0xaa, 0xac, 0x06, 0x5a, 0x3a, 0x6d, 0x35, 0x74, 0xda, 0x83, 0xc1, 0x2c,
	0xa1, 0x19, 0x0b, 0x47, 0xd2, 0x5e, 0x81, 0xa6, 0x7a, 0xdb, 0x6d, 0xf5, 0x74, 0xbf, 0x42, 0xa3,
	0x5f, 0x6b, 0x3d, 0xc7, 0x4d, 0x3d, 0x2d, 0x91, 0x26, 0x0d, 0x91, 0x9e, 0xc2, 0xe4, 0xa8, 0x48,
	0x57, 0xc2, 0xea, 0xc7, 0xa3, 0xb2, 0xb8, 0x5a, 0x57, 0x4d, 0xa1, 0x20, 0x00, 0x3f, 0x2e, 0x74,
	0xcd, 0xbc, 0x48, 0x9e, 0xc9, 0x33, 0xb8, 0x73, 0x9e, 0xdf, 0xda, 0x7b, 0x06, 0x93, 0x03, 0x4a,
	0x8f, 0x4a, 0xce, 0x72, 0x39, 0x7f, 0x21, 0x6c, 0x61, 0x98, 0x6f, 0x6a, 0x67, 0x03, 0xcd, 0xcb,
	0xa3, 0x3a, 0x80, 0x81, 0x18, 0xe3, 0x90, 0x2d, 0x3e, 0x2c, 0xc6, 0x53, 0x98, 0xcc, 0x16, 0x45,
	0xfa, 0xea, 0xd6, 0x15, 0xb8, 0xb8, 0xad, 0xf7, 0x97, 0xb0, 0x83, 0x6e, 0xcf, 0x93, 0x92, 0x9a,
	0x21, 0x79, 0x4b, 0xd3, 0x92, 0x1f, 0xda, 0xa6, 0x22, 0x78, 0x08, 0x23, 0x03, 0xf5, 0x48, 0xec,
	0x9a, 0x91, 0x58, 0x69, 0xd3, 0xa8, 0xb6, 0x20, 0x7f, 0x3a, 0x30, 0x32, 0xd7, 0xc8, 0x82, 0x7f,
	0xd7, 0x2c, 0x0a, 0x61, 0x03, 0xe1, 0x09, 0x37, 0x95, 0x59, 0x3a, 0x06, 0x9b, 0x37, 0x7b, 0x3c,
	0x0c, 0xc6, 0xf6, 0xad, 0xf8, 0x15, 0x13, 0x72, 0x12, 0xbc, 0x48, 0x81, 0xe0, 0x33, 0x00, 0x93,
	0xf3, 0x9c, 0xca, 0x49, 0xf0, 0x22, 0xeb, 0x86, 0x3c, 0x94, 0xef, 0x32, 0x4f, 0xf6, 0xba, 0x65,
	0xed, 0x6c, 0x58, 0x27, 0xfa, 0xdf, 0x07, 0xef, 0x67, 0x6e, 0x15, 0xd2, 0x6d, 0xef, 0xd5, 0x88,
	0xa5, 0xfc, 0x8d, 0xf5, 0x43, 0x65, 0x30, 0x79, 0x01, 0x9f, 0xa8, 0xf3, 0x07, 0x92, 0xe0, 0xf2,
	0xb2, 0x95, 0x9a, 0x6e, 0x28, 0x55, 0x2f, 0xaf, 0xb4, 0xa9, 0xd2, 0x1f, 0x0e, 0xf8, 0xe9, 0xff,
	0xa1, 0x50, 0x00, 0xfe, 0x49, 0x51, 0x31, 0xbd, 0xc1, 0xe4, 0xb9, 0x5b, 0x35, 0x92, 0x03, 0x1c,
	0xd0, 0xba, 0xcc, 0x36, 0x9f, 0xd3, 0xc3, 0xe7, 0x6e, 0x76, 0x44, 0x2c, 0x63, 0x7b, 0x2a, 0xb6,
	0x04, 0x5d, 0x59, 0x90, 0x73, 0xf5, 0x7b, 0x68, 0x08, 0xdf, 0xf1, 0xe1, 0x9d, 0x64, 0x26, 0xac,
	0x67, 0x85, 0x7d, 0x0c, 0x10, 0x27, 0x99, 0x51, 0xe0, 0x01, 0x6c, 0x69, 0xa4, 0x05, 0x18, 0x1b,
	0x01, 0xaa, 0x24, 0x8b, 0xcc, 0x1b, 0xf9, 0x16, 0xbc, 0x2a, 0xc9, 0x70, 0x57, 0xc4, 0x49, 0x26,
	0xa9, 0xd4, 0x37, 0x1b, 0x28, 0x3f, 0x2b, 0xc9, 0x6a, 0xbd, 0x15, 0x20, 0x0f, 0xe4, 0x9e, 0x8e,
	0x93, 0x4c, 0xaf, 0xa0, 0x6e, 0x67, 0xf2, 0x0c, 0x00, 0xbf, 0x54, 0xdb, 0xd5, 0xa1, 0x1c, 0x2b,
	0x94, 0xed, 0xed, 0x36, 0xbd, 0x3f, 0x87, 0xed, 0x43, 0xb6, 0xe8, 0x73, 0x26, 0xbf, 0xc2, 0xee,
	0xf9, 0x92, 0x26, 0x15, 0xc3, 0x36, 0xd4, 0x96, 0x6f, 0xfb, 0x15, 0xb4, 0x2a, 0xe2, 0xf6, 0x54,
	0x64, 0x0a, 0x77, 0x74, 0xb0, 0x77, 0x6d, 0xa8, 0x27, 0x2d, 0xcb, 0xf7, 0x2d, 0xfa, 0xc5, 0x50,
	0xfe, 0xcf, 0xe2, 0xf1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xff, 0x86, 0x7e, 0xee, 0x71, 0x0c,
	0x00, 0x00,
}
