// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currentInfo.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId              string   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentInfo) Reset()         { *m = CurrentInfo{} }
func (m *CurrentInfo) String() string { return proto.CompactTextString(m) }
func (*CurrentInfo) ProtoMessage()    {}
func (*CurrentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e82056499578dc2, []int{0}
}

func (m *CurrentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentInfo.Unmarshal(m, b)
}
func (m *CurrentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentInfo.Marshal(b, m, deterministic)
}
func (m *CurrentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentInfo.Merge(m, src)
}
func (m *CurrentInfo) XXX_Size() int {
	return xxx_messageInfo_CurrentInfo.Size(m)
}
func (m *CurrentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentInfo proto.InternalMessageInfo

func (m *CurrentInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CurrentInfo) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentInfo)(nil), "user.CurrentInfo")
}

func init() { proto.RegisterFile("currentInfo.proto", fileDescriptor_3e82056499578dc2) }

var fileDescriptor_3e82056499578dc2 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2e, 0x2d, 0x2a,
	0x4a, 0xcd, 0x2b, 0xf1, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29,
	0x2d, 0x4e, 0x2d, 0x52, 0x72, 0xe4, 0xe2, 0x76, 0x46, 0x48, 0x09, 0x89, 0x73, 0xb1, 0x83, 0x84,
	0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21,
	0x49, 0x2e, 0x8e, 0x92, 0xa2, 0xc4, 0xe4, 0x54, 0x90, 0x0c, 0x13, 0x58, 0x86, 0x1d, 0xcc, 0xf7,
	0x4c, 0x49, 0x62, 0x03, 0x9b, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x11, 0x46, 0x4d, 0x8f,
	0x64, 0x00, 0x00, 0x00,
}
