// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscribe.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登录返回值
type SubscribeData struct {
	Source               int32    `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	TypeName             string   `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Params               *any.Any `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeData) Reset()         { *m = SubscribeData{} }
func (m *SubscribeData) String() string { return proto.CompactTextString(m) }
func (*SubscribeData) ProtoMessage()    {}
func (*SubscribeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d2980c9543da44, []int{0}
}

func (m *SubscribeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeData.Unmarshal(m, b)
}
func (m *SubscribeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeData.Marshal(b, m, deterministic)
}
func (m *SubscribeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeData.Merge(m, src)
}
func (m *SubscribeData) XXX_Size() int {
	return xxx_messageInfo_SubscribeData.Size(m)
}
func (m *SubscribeData) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeData.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeData proto.InternalMessageInfo

func (m *SubscribeData) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *SubscribeData) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *SubscribeData) GetParams() *any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscribeData)(nil), "pb.SubscribeData")
}

func init() { proto.RegisterFile("subscribe.proto", fileDescriptor_38d2980c9543da44) }

var fileDescriptor_38d2980c9543da44 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x4d, 0x2a,
	0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92,
	0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x27, 0xe6,
	0x55, 0x42, 0xa4, 0x95, 0x8a, 0xb8, 0x78, 0x83, 0x61, 0x3a, 0x5c, 0x12, 0x4b, 0x12, 0x85, 0xc4,
	0xb8, 0xd8, 0x8a, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0,
	0x3c, 0x21, 0x69, 0x2e, 0xce, 0x92, 0xca, 0x82, 0xd4, 0xf8, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x0e, 0x90, 0x80, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0x0e, 0x17, 0x5b,
	0x41, 0x62, 0x51, 0x62, 0x6e, 0xb1, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc4,
	0x46, 0x3d, 0x98, 0x8d, 0x7a, 0x8e, 0x79, 0x95, 0x41, 0x50, 0x35, 0x49, 0x6c, 0x60, 0x51, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x87, 0x87, 0x24, 0xac, 0x00, 0x00, 0x00,
}
